// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"bg-white text-black py-10 sm:py-16 border-black\"><div class=\"container mx-auto px-3 sm:px-4 flex flex-col lg:flex-row justify-between items-start gap-8 sm:gap-10\"><!-- Left Text Content --><div class=\"lg:w-1/2\"><!-- Tag --><div class=\"inline-block bg-brutalist-yellow text-brutalist-black font-bold px-4 py-1 uppercase mb-6\">Why YesFix</div><!-- Title --><h2 class=\"text-2xl sm:text-4xl md:text-5xl uppercase tracking-wider text-brutalist-black font-brutalist mb-3 sm:mb-4 leading-snug sm:leading-tight\"><span>Why Choose <span class=\"text-brutalist-yellow\">YES</span>Fix!</span><br>THE GAMUSA OF SERVICES</h2><!-- Paragraph --><p class=\"mb-4 sm:mb-6 uppercase text-sm sm:text-base text-brutalist-black font-bold tracking-wide\">We don’t just clean or fix — we bring peace of mind to your doorstep.</p><!-- Common Problems --><h3 class=\"text-lg sm:text-xl md:text-2xl uppercase tracking-wider text-brutalist-grey font-brutalist mb-3 sm:mb-4\">Common Problems</h3><ul class=\"list-disc pl-4 sm:pl-5 space-y-2 uppercase text-sm sm:text-base text-brutalist-black font-bold tracking-wide\"><li>Unreliable & Delayed Local Services</li><li>Lack of Trust & Standard Pricing</li><li>No Quick Commerce in Services</li><li>Corporate Maintenance Gaps</li></ul></div><!-- Right Image Column (Animated on Scroll) --><div class=\"lg:w-1/2 flex justify-end js-scroll opacity-0\" data-animate=\"bounce-in-right\"><img src=\"/public/about.png\" alt=\"YesFix Solutions\" class=\"w-full max-w-xs sm:max-w-md md:max-w-lg lg:max-w-xl ml-auto\"></div></div></section><script src=\"/public/js/scrollAnimations.js\" defer></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
