// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Compare() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"bg-white text-brutalist-black pt-2 pb-16 px-6\"><div class=\"max-w-6xl mx-auto\"><div class=\"grid md:grid-cols-1 gap-8\"><!-- Problems Column --><!-- Solutions Column --><div class=\"bg-brutalist-light-yellow border-l-4 border-brutalist-yellow p-6 shadow-md animate-slide-in-right\"><h3 class=\"text-2xl uppercase tracking-wider text-red font-brutalist mb-4\">YesFix Solutions</h3><ul class=\"list-disc pl-5 space-y-2 uppercase text-lg text-brutalist-black font-bold tracking-wide\"><li>Background-verified local professionals</li><li>₹200 cashback if we arrive late (T&C apply)</li><li>30-Minute Express Visits (limited availability)</li><li>Live tracking of professionals</li><li>30-Day Guarantee on all services</li><li>Friendly Assamese support team</li><li>Transparent pricing – No hidden charges</li></ul></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
