// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// templ Footer() {
// <footer class="w-full bg-base-100 shadow-sm shadow-base-300/20 py-3">
// <div class="container mx-auto flex flex-wrap items-center justify-between gap-4 px-4">
// <div class="font-brutalist text-sm text-base-content/70">
// &copy; 2025 YESFIX. ALL RIGHTS RESERVED.
// </div>
// <div class="flex items-center gap-4">
// <a href="#" class="font-brutalist text-base-content/70 hover:text-base-content">PRIVACY POLICY</a>
// <a href="#" class="font-brutalist text-base-content/70 hover:text-base-content">TERMS OF SERVICE</a>
// </div>
// </div>
// </footer>
// }
func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"bg-white text-black border-t-2 border-black pt-12 pb-8 px-4\"><div class=\"max-w-screen-xl mx-auto flex flex-col lg:flex-row justify-between gap-8\"><!-- Left: Logo and Description --><div class=\"flex flex-col items-start\"><!-- Logo Image --><div class=\"mb-4\"><img src=\"/public/logo.png\" alt=\"YesFix Logo\" class=\"w-32\"></div><!-- Description --><p class=\"max-w-sm text-sm uppercase leading-relaxed\">Proudly Serving Dibrugarh<br></p></div><!-- Right: Social Media Icons --><div class=\"flex flex-col items-start\"><a href=\"/about\" class=\"hover:text-brutalist-yellow transition-all\"><h3 class=\"uppercase font-bold mb-4\">About</h3></a><h3 class=\"uppercase font-bold mb-4\">Follow Us</h3><div class=\"flex gap-2\"><a href=\"https://www.facebook.com/profile.php?id=61574118658025#\" target=\"_blank\" class=\"rounded-xl bg-black w-10 h-10 flex items-center justify-center hover:bg-brutalist-yellow transition-all\"><i class=\"fab fa-facebook-f text-white\"></i></a> <a href=\"https://www.instagram.com/yesfix_assam/\" target=\"_blank\" class=\"rounded-xl bg-black w-10 h-10 flex items-center justify-center hover:bg-brutalist-yellow transition-all\"><i class=\"fab fa-instagram text-white\"></i></a> <a href=\"https://www.linkedin.com/in/yes-fix-a7335b363 \" target=\"_blank\" class=\"rounded-xl bg-black w-10 h-10 flex items-center justify-center hover:bg-brutalist-yellow transition-all\"><i class=\"fab fa-whatsapp text-white\"></i></a></div></div></div><!-- Bottom Row --><div class=\"mt-10 border-t-2 border-black pt-4 text-center text-sm\"><p class=\"mb-2\">© 2025 YESFIX. ALL RIGHTS RESERVED.</p><div class=\"flex justify-center gap-6 uppercase font-semibold text-xs cursor-pointer\"><p class=\"mb-2\">Made with ❤️ by <a class=\"hover:underline\">BIN Labs</a></p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
