// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(mobileButtons templ.Component, desktopButtons templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"announcementBar\" class=\"transition-opacity duration-300 w-full bg-brutalist-light-yellow text-black text-center py-2 px-4 text-sm font-semibold flex items-center overflow-hidden relative\"><div class=\"bg-green w-full marquee-text font-semibold text-sm px-4\">📣YesFix! app is now available on both iOS and Android! </div><style>\r\n        @keyframes marquee-left {\r\n            0% {\r\n                transform: translateX(99%);\r\n            }\r\n\r\n            100% {\r\n                transform: translateX(-100%);\r\n            }\r\n        }\r\n\r\n        .marquee-text {\r\n            display: inline-block;\r\n            white-space: nowrap;\r\n            animation: marquee-left 15s linear infinite;\r\n        }\r\n    </style></div><nav class=\"sticky top-0 w-full bg-base-100 bg-white shadow-sm shadow-base-300/20 py-3 z-50\"><!-- Announcement Bar --><div class=\"container mx-auto flex flex-wrap items-center justify-between gap-4 px-4\"><!-- Logo --><div class=\"flex items-center gap-2\"><a class=\"text-xl font-bold text-base-content no-underline\" href=\"/\"><img src=\"/public/logo.png\" alt=\"Yesfix\" class=\"w-32 h-16 object-contain rounded\"></a></div><!-- Desktop Buttons -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktopButtons.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Mobile Menu Button --><div class=\"md:hidden \"><button id=\"menu-toggle\" class=\"text-xl focus:outline-none\" onclick=\"toggleMobileMenuIcon(); \"><span id=\"menu-icon\">☰</span></button></div></div><!-- Mobile Menu --><div id=\"mobile-menu\" class=\"hidden text-sm transition-all duration-300 ease-in-out px-2 pt-4 space-y-auto bg-white border-t-2 border-black font-poppins font-bold text-brutalist-black \">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = mobileButtons.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></nav><!-- External Script --><script src=\"/public/js/navbar.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
