// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Prebook() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"reviews\" class=\"bg-white text-white py-16\"><div class=\"max-w-screen-xl mx-auto px-4 flex flex-col lg:flex-row gap-10 items-start\"><!-- Left: Offer + Image --><div class=\"w-full lg:w-1/2\"><!-- Tag --><div class=\"inline-block bg-brutalist-yellow text-brutalist-black font-bold px-4 py-1 uppercase mb-6\">Pre-book</div><!-- Title --><h2 class=\"text-4xl sm:text-5xl uppercase text-brutalist-yellow font-brutalist mb-4\">Pre- <span class=\"text-brutalist-black\">book now!</span></h2><!-- Offer Text --><p class=\"uppercase text-base sm:text-lg text-brutalist-black font-bold tracking-wide mb-8 leading-relaxed\">🎉 Early Bird Offers<br>✔ First 20 Customers – Get FREE Service<br>✔ Next 50 Customers – Get 50% OFF<br>✔ All Services Come With a 30-Day Guarantee<br>🔥 Offer Ends Soon – Limited-Time Only</p><!-- Responsive Image --><div class=\"flex justify-center lg:justify-start mt-6\"><img src=\"public/pre.png\" alt=\"YesFix Solutions\" class=\"w-full max-w-xs sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl\"></div></div><!-- Right: Prebooking Form --><div id=\"prebook-form\" class=\"w-full lg:w-1/2 bg-white text-black p-6 sm:p-8 shadow-[6px_6px_0_0_black] border-2 border-black\">hello</div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
