// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	Cid       string             `db:"cid" json:"cid"`
	Firstname string             `db:"firstname" json:"firstname"`
	Midname   pgtype.Text        `db:"midname" json:"midname"`
	Lastname  string             `db:"lastname" json:"lastname"`
	Email     string             `db:"email" json:"email"`
	Phone     string             `db:"phone" json:"phone"`
	City      string             `db:"city" json:"city"`
	Locality  string             `db:"locality" json:"locality"`
	Pincode   string             `db:"pincode" json:"pincode"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PrebookDatum struct {
	Uid       string             `db:"uid" json:"uid"`
	Firstname string             `db:"firstname" json:"firstname"`
	Lastname  string             `db:"lastname" json:"lastname"`
	Email     string             `db:"email" json:"email"`
	Phone     string             `db:"phone" json:"phone"`
	City      string             `db:"city" json:"city"`
	Locality  string             `db:"locality" json:"locality"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	Usid      string             `db:"usid" json:"usid"`
	Firstname string             `db:"firstname" json:"firstname"`
	Lastname  string             `db:"lastname" json:"lastname"`
	Email     string             `db:"email" json:"email"`
	Phone     string             `db:"phone" json:"phone"`
	City      string             `db:"city" json:"city"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
