// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
)

const insertUserTest = `-- name: InsertUserTest :one
INSERT INTO users(usid, firstname,lastname,email,phone,city) VALUES($1, $2, $3, $4, $5, $6) RETURNING usid, firstname, lastname, email, phone, city, created_at, updated_at, deleted_at
`

type InsertUserTestParams struct {
	Usid      string `db:"usid" json:"usid"`
	Firstname string `db:"firstname" json:"firstname"`
	Lastname  string `db:"lastname" json:"lastname"`
	Email     string `db:"email" json:"email"`
	Phone     string `db:"phone" json:"phone"`
	City      string `db:"city" json:"city"`
}

func (q *Queries) InsertUserTest(ctx context.Context, arg InsertUserTestParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserTest,
		arg.Usid,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Phone,
		arg.City,
	)
	var i User
	err := row.Scan(
		&i.Usid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
