// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	InsertUserTest(ctx context.Context, arg InsertUserTestParams) (PrebookDatum, error)
}

var _ Querier = (*Queries)(nil)
